repository: BrianOtto/brianotto.github.io

url: http://reboldocs.brianotto.com

encoding: utf-8

kramdown:
  syntax_highlighter_opts:
    disable: true

collections:
  3.0_sections:
    output: false
  
  3.0_chapters:
    output: true
    permalink: /docs/3.0/:name
  
  3.0_pages:
    output: true
    permalink: /docs/3.0/:name
  
  archived_sections:
    output: false
  
  archived_chapters:
    output: true
    permalink: /docs/archived/:name
  
  archived_pages:
    output: true
    permalink: /docs/archived/:path
  
  versions:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  
  -
    scope:
      type: "3.0_chapters"
    values:
      layout: "docs"
  
  -
    scope:
      type: "3.0_pages"
    values:
      layout: "docs"
  
  -
    scope:
      type: "archived_chapters"
    values:
      layout: "docs"
  
  -
    scope:
      type: "archived_pages"
    values:
      layout: "docs"