repository: BrianOtto/brianotto.github.io

highlighter: none

kramdown:
  syntax_highlighter_opts:
     disable: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "docs"
    values:
      layout: "docs"